// ignore_for_file: unused_import

import 'package:flutter/material.dart';
import 'package:xpense_flutter_web/pages/containers/container1.dart';
import 'package:xpense_flutter_web/pages/containers/container2.dart';

import 'package:xpense_flutter_web/pages/containers/container3.dart';
import 'package:xpense_flutter_web/pages/containers/container4.dart';
import 'package:xpense_flutter_web/pages/containers/container5.dart';
// ignore: duplicate_import
import 'package:flutter/material.dart';
import 'package:xpense_flutter_web/utils/constants.dart';
import 'package:xpense_flutter_web/widgets/navBar.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {



// void main() {
//   runApp(const FigmaToCodeApp());
// }

// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           DesktopCs(),
//         ]),
//       ),
//     );
//   }
// }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 832,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1600,
                  height: 915,
                  decoration: BoxDecoration(color: Color(0xFFFAF9E7)),
                  child: Stack(children: []),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Opacity(
                  opacity: 0.05,
                  child: Container(
                    width: 1440,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 3357,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 480),
                        Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 3357,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 480),
                        Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 3357,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 480),
                        Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 3357,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 480),
                        Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 3357,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1520,
                  height: 112.94,
                  decoration: BoxDecoration(
                    color: Color(0xFFF6F4D2),
                    border: Border(
                      left: BorderSide(color: Color(0xFF4B5563)),
                      top: BorderSide(color: Color(0xFF4B5563)),
                      right: BorderSide(color: Color(0xFF4B5563)),
                      bottom: BorderSide(width: 1.06, color: Color(0xFF4B5563)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 1306.78,
                        top: 44.33,
                        child: Container(
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Text(
                                'Menu',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 25.33,
                                  fontFamily: 'Manrope',
                                  fontWeight: FontWeight.w400,
                                  height: 0.03,
                                ),
                              ),
                              const SizedBox(width: 15.83),
                              Container(
                                width: 25.33,
                                height: 25.33,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Stack(children: []),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 693,
                        top: 50,
                        child: Container(
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Home',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 19,
                                  fontFamily: 'Manrope',
                                  fontWeight: FontWeight.w400,
                                  height: 0.04,
                                ),
                              ),
                              const SizedBox(width: 116.11),
                              Text(
                                'Talk',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 19,
                                  fontFamily: 'Manrope',
                                  fontWeight: FontWeight.w600,
                                  height: 0.04,
                                ),
                              ),
                              const SizedBox(width: 116.11),
                              Text(
                                'Get Diagnosed',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 19,
                                  fontFamily: 'Manrope',
                                  fontWeight: FontWeight.w400,
                                  height: 0.04,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 25,
                        child: Container(
                          width: 190,
                          height: 63,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/190x63"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 693,
                        top: 71,
                        child: Container(
                          width: 52,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.17,
                                strokeAlign: BorderSide.strokeAlignCenter,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 107.67,
                top: 1936.94,
                child: Container(
                  width: 1412.33,
                  padding: const EdgeInsets.all(10.56),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(width: 422.22, height: 529.89),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 107.67,
                top: 1936.94,
                child: Container(
                  width: 1412.33,
                  padding: const EdgeInsets.all(10.56),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 422.22,
                                height: 529.89,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/422x530"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 30.61),
                      Container(
                        width: 422.22,
                        height: 529.89,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(width: 422.22, height: 529.89),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 107.67,
                top: 950,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10.56),
                        decoration: BoxDecoration(color: Colors.white),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 620.67,
                              height: 803.28,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/621x803"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(height: 25.33),
                            Container(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          'Project name',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 29.56,
                                            fontFamily: 'Vollkorn',
                                            fontWeight: FontWeight.w600,
                                            height: 0.03,
                                          ),
                                        ),
                                        const SizedBox(height: 8.44),
                                        Text(
                                          'Project type',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 16.89,
                                            fontFamily: 'Manrope',
                                            fontWeight: FontWeight.w400,
                                            height: 0.05,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 25.33),
                                  Container(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          height: 27.44,
                                          padding: const EdgeInsets.all(10.56),
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                                              borderRadius: BorderRadius.circular(19),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                'Industry',
                                                style: TextStyle(
                                                  color: Color(0xFF565656),
                                                  fontSize: 12.67,
                                                  fontFamily: 'Manrope',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.06,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 42.22),
                      Container(
                        padding: const EdgeInsets.all(10.56),
                        decoration: BoxDecoration(color: Colors.white),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 620.67,
                              height: 803.28,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/621x803"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(height: 25.33),
                            Container(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          'Project name',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 29.56,
                                            fontFamily: 'Vollkorn',
                                            fontWeight: FontWeight.w600,
                                            height: 0.03,
                                          ),
                                        ),
                                        const SizedBox(height: 8.44),
                                        Text(
                                          'Project type',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 16.89,
                                            fontFamily: 'Manrope',
                                            fontWeight: FontWeight.w400,
                                            height: 0.05,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 25.33),
                                  Container(
                                    width: 70.11,
                                    padding: const EdgeInsets.all(10.56),
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                                        borderRadius: BorderRadius.circular(19),
                                      ),
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Text(
                                          'Industry',
                                          style: TextStyle(
                                            color: Color(0xFF565656),
                                            fontSize: 12.67,
                                            fontFamily: 'Manrope',
                                            fontWeight: FontWeight.w400,
                                            height: 0.06,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 89.78,
                top: 2638.89,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10.56),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    width: 620.67,
                                    height: 343.06,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: NetworkImage("https://via.placeholder.com/621x343"),
                                        fit: BoxFit.fill,
                                      ),
                                    ),
                                  ),
                                  const SizedBox(height: 25.33),
                                  Container(
                                    width: double.infinity,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                'Project name',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 29.56,
                                                  fontFamily: 'Vollkorn',
                                                  fontWeight: FontWeight.w600,
                                                  height: 0.03,
                                                ),
                                              ),
                                              const SizedBox(height: 8.44),
                                              Text(
                                                'Project type',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 16.89,
                                                  fontFamily: 'Manrope',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.05,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        const SizedBox(width: 25.33),
                                        Container(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                height: 27.44,
                                                padding: const EdgeInsets.all(10.56),
                                                decoration: ShapeDecoration(
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                                                    borderRadius: BorderRadius.circular(19),
                                                  ),
                                                ),
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Text(
                                                      'Industry',
                                                      style: TextStyle(
                                                        color: Color(0xFF565656),
                                                        fontSize: 12.67,
                                                        fontFamily: 'Manrope',
                                                        fontWeight: FontWeight.w400,
                                                        height: 0.06,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 45.39),
                            Container(
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    width: 620.67,
                                    height: 343.06,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: NetworkImage("https://via.placeholder.com/621x343"),
                                        fit: BoxFit.fill,
                                      ),
                                    ),
                                  ),
                                  const SizedBox(height: 25.33),
                                  Container(
                                    width: double.infinity,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                'Project name',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 29.56,
                                                  fontFamily: 'Vollkorn',
                                                  fontWeight: FontWeight.w600,
                                                  height: 0.03,
                                                ),
                                              ),
                                              const SizedBox(height: 8.44),
                                              Text(
                                                'Project type',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 16.89,
                                                  fontFamily: 'Manrope',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.05,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        const SizedBox(width: 25.33),
                                        Container(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                height: 27.44,
                                                padding: const EdgeInsets.all(10.56),
                                                decoration: ShapeDecoration(
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                                                    borderRadius: BorderRadius.circular(19),
                                                  ),
                                                ),
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Text(
                                                      'Industry',
                                                      style: TextStyle(
                                                        color: Color(0xFF565656),
                                                        fontSize: 12.67,
                                                        fontFamily: 'Manrope',
                                                        fontWeight: FontWeight.w400,
                                                        height: 0.06,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 21.11),
                      Container(
                        padding: const EdgeInsets.all(10.56),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 620.67,
                              height: 803.28,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/621x803"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(height: 25.33),
                            Container(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          'Project name',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 29.56,
                                            fontFamily: 'Vollkorn',
                                            fontWeight: FontWeight.w600,
                                            height: 0.03,
                                          ),
                                        ),
                                        const SizedBox(height: 8.44),
                                        Text(
                                          'Project type',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 16.89,
                                            fontFamily: 'Manrope',
                                            fontWeight: FontWeight.w400,
                                            height: 0.05,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 25.33),
                                  Container(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          height: 27.44,
                                          padding: const EdgeInsets.all(10.56),
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                                              borderRadius: BorderRadius.circular(19),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                'Industry',
                                                style: TextStyle(
                                                  color: Color(0xFF565656),
                                                  fontSize: 12.67,
                                                  fontFamily: 'Manrope',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.06,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 3664.89,
                child: Container(
                  width: 1520,
                  height: 96.06,
                  padding: const EdgeInsets.all(10.56),
                  decoration: BoxDecoration(
                    border: Border(
                      left: BorderSide(color: Color(0xFF4B5563)),
                      top: BorderSide(width: 1.06, color: Color(0xFF4B5563)),
                      right: BorderSide(color: Color(0xFF4B5563)),
                      bottom: BorderSide(color: Color(0xFF4B5563)),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: 'Designed by ',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 16.89,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.05,
                              ),
                            ),
                            TextSpan(
                              text: 'KingSamuel',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 16.89,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.05,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 3664.89,
                child: Container(
                  width: 1520,
                  height: 96.06,
                  padding: const EdgeInsets.all(10.56),
                  decoration: BoxDecoration(
                    border: Border(
                      left: BorderSide(color: Color(0xFF4B5563)),
                      top: BorderSide(width: 1.06, color: Color(0xFF4B5563)),
                      right: BorderSide(color: Color(0xFF4B5563)),
                      bottom: BorderSide(color: Color(0xFF4B5563)),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: 'Designed by ',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 16.89,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.05,
                              ),
                            ),
                            TextSpan(
                              text: 'KingSamuel',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 16.89,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.05,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 323.11,
                top: 836,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 108.28,
                        padding: const EdgeInsets.all(10.56),
                        decoration: ShapeDecoration(
                          color: Color(0xFF565656),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(19),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Healthcare',
                              style: TextStyle(
                                color: Color(0xFFDDDDDD),
                                fontSize: 12.67,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.06,
                              ),
                            ),
                            Container(
                              width: 16.89,
                              height: 16.89,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(children: []),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 29.56),
                      Container(
                        width: 87.28,
                        padding: const EdgeInsets.all(10.56),
                        decoration: ShapeDecoration(
                          color: Color(0xFF565656),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(19),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Fintech',
                              style: TextStyle(
                                color: Color(0xFFDDDDDD),
                                fontSize: 12.67,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.06,
                              ),
                            ),
                            Container(
                              width: 16.89,
                              height: 16.89,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(children: []),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 29.56),
                      Container(
                        width: 72.28,
                        padding: const EdgeInsets.all(10.56),
                        decoration: ShapeDecoration(
                          color: Color(0xFF565656),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(19),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'hello',
                              style: TextStyle(
                                color: Color(0xFFDDDDDD),
                                fontSize: 12.67,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.06,
                              ),
                            ),
                            Container(
                              width: 16.89,
                              height: 16.89,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(children: []),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 29.56),
                      Container(
                        width: 83.11,
                        padding: const EdgeInsets.all(10.56),
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                            borderRadius: BorderRadius.circular(19),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Metaverse',
                              style: TextStyle(
                                color: Color(0xFF565656),
                                fontSize: 12.67,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.06,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 29.56),
                      Container(
                        padding: const EdgeInsets.all(10.56),
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 1.06, color: Color(0xFF565656)),
                            borderRadius: BorderRadius.circular(19),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Crypto',
                              style: TextStyle(
                                color: Color(0xFF565656),
                                fontSize: 12.67,
                                fontFamily: 'Manrope',
                                fontWeight: FontWeight.w400,
                                height: 0.06,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 73,
                top: 284,
                child: Container(width: 261.09, height: 12),
              ),
              Positioned(
                left: 75,
                top: 307,
                child: SizedBox(
                  width: 793,
                  height: 112.59,
                  child: Text(
                    'Let’s talk',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 100,
                      fontFamily: 'Lustria',
                      fontWeight: FontWeight.w400,
                      height: 0.01,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 680,
                top: 420,
                child: SizedBox(
                  width: 537,
                  height: 110,
                  child: Text(
                    'You are a woman. You have struggled with mental health your entire life. You have never even considered getting a diagnosis would be this easy, until AMERO',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 25.33,
                      fontFamily: 'Manrope',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1014,
                top: 75,
                child: Container(
                  width: 130,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 3.17,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111,
                top: 420,
                child: Container(
                  width: 346.78,
                  height: 26,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Container(
                          width: 41.22,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.17,
                                strokeAlign: BorderSide.strokeAlignCenter,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 51.78,
                        top: 0,
                        child: Text(
                          'A diagnosis has never been easier  ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 19,
                            fontFamily: 'Manrope',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -0.03,
                top: 809.38,
                child: Container(
                  width: 1520.06,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1.06,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.black.withOpacity(0.10000000149011612),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
//   @override
//   Widget build(BuildContext context) {
//     w = MediaQuery.of(context).size.width;
//     h = MediaQuery.of(context).size.height;
//     return Scaffold(
//         body: SingleChildScrollView(
//       child: Container(
//         child: Column(
//           children: [
//             NavBar(),
//             SizedBox(
//               height: 100,
//             ),
//             Container1(),
//             Container2(),
//             Container3(),
//             Container4(),
//             Container5()

//             // MainContent()
//           ],
//         ),
//       ),
//     ));
//   }
// }
